// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnN0bW21KPaHFpFL67brZUTkfLLqymEeY',
    appId: '1:456632748430:web:b6a16aadde4ec7aad63cdf',
    messagingSenderId: '456632748430',
    projectId: 'theearthmap-a3693',
    authDomain: 'theearthmap-a3693.firebaseapp.com',
    storageBucket: 'theearthmap-a3693.firebasestorage.app',
    measurementId: 'G-0H356MDD3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz1-C4gwspMaDNwJknygSND_YQnR_NcTo',
    appId: '1:456632748430:android:e8dee1d2c255db8bd63cdf',
    messagingSenderId: '456632748430',
    projectId: 'theearthmap-a3693',
    storageBucket: 'theearthmap-a3693.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqfe0V_yimnr07eYNkJYYc2fWbkLdTv-Y',
    appId: '1:456632748430:ios:a182e44165fcb217d63cdf',
    messagingSenderId: '456632748430',
    projectId: 'theearthmap-a3693',
    storageBucket: 'theearthmap-a3693.firebasestorage.app',
    iosBundleId: 'com.example.liveEarthMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqfe0V_yimnr07eYNkJYYc2fWbkLdTv-Y',
    appId: '1:456632748430:ios:a182e44165fcb217d63cdf',
    messagingSenderId: '456632748430',
    projectId: 'theearthmap-a3693',
    storageBucket: 'theearthmap-a3693.firebasestorage.app',
    iosBundleId: 'com.example.liveEarthMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnN0bW21KPaHFpFL67brZUTkfLLqymEeY',
    appId: '1:456632748430:web:73c788889c1e8eebd63cdf',
    messagingSenderId: '456632748430',
    projectId: 'theearthmap-a3693',
    authDomain: 'theearthmap-a3693.firebaseapp.com',
    storageBucket: 'theearthmap-a3693.firebasestorage.app',
    measurementId: 'G-YPD6FBYSQE',
  );
}
